blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import (
        post_update,
        post_list,
        post_detail,
        post_create,
        post_delete
    )


urlpatterns = [
    url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),

]

djangoBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import blog.views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include("blog.urls", namespace="posts")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db.models.signals import pre_save

from django.conf import settings
# Create your models here.
from django.urls import reverse
from django.utils.text import slugify

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.FileField(null=True, blank=True)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.title

    def get_short_content(self):
        return self.content[:500]

    def get_absolute_path(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_reciver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_reciver, sender=Post)

blog/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image"
        ]

blog/views.py
from django.http import Http404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib import messages

from urllib.parse import quote_plus


from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render

# Create your views here.
from django.views.decorators.csrf import csrf_protect

from .models import Post
from .forms import PostForm


def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    if not request.user.is_authenticated():
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Successfully created")
        return HttpResponseRedirect(instance.get_absolute_path())
    else:
        messages.success(request, "Error")

    context = {
        "form": form
    }
    return render(request, "post_form.html", context)

def post_detail(request, slug):
    instance = get_object_or_404(Post, slug=slug)
    context = {
        "title": instance.title,
        "instance": instance,
    }
    return render(request, "post_detail.html", context)

def post_list(request):
    queryset_list = Post.objects.all().order_by("-timestamp")
    paginator = Paginator(queryset_list, 5)  # Show 25 contacts per page

    page_request_var = "page"
    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    context = {
        "post_list": queryset,
        "title": "List",
        "page_request_var": page_request_var,
    }
    return render(request, "post_list.html", context)


def post_update(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_path())

    context = {
        "title": instance.title,
        "instance": instance,
        "form": form,
    }
    return render(request, "post_form.html", context)

def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, "Successfully deleted")
    return redirect("posts:list")

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %} Blog {% endblock %}</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/journal/bootstrap.min.css" rel="stylesheet" integrity="sha384-1L94saFXWAvEw88RkpRz8r28eQMvt7kG9ux3DdCqya/P3CfLNtgqzMnyaUa49Pl2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'base.css' %}">
</head>
<body>
<div class="container">
    {% block content %}{% endblock %}
</div>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}

{% block head_title %}
    {{ instance.title }} | {{ block.super }}
{% endblock %}



{% block content %}
    <div class="col-sm-8 col-sm-offset-2">
        {% if instance.image %}
            <img src="{{ instance.image.url }}" alt="" class="img-responsive">
        {% endif %}
        <h1>{{ title }}
            <small>{{ instance.timestamp }}</small>
        </h1>
        {% if instance.user.get_full_name %}
            <p>Author: {{ instance.user.get_full_name }}</p>
        {% endif %}
        {{ instance.content|linebreaks }}<br>
        <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
            Facebook
        </a>
        <small>|</small>
        <a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>
            Google
        </a>
        <small>|</small>
        <a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}&title={{ instance.title|urlify }}">
            Reddit
        </a>
        <small>|</small>
        <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&summary={{ instance.content|urlify }}&source=http://swiftforentrepreneurs.com/">
            Linkedin
        </a>

    </div>
{% endblock %}

templates/post_form.html
{% extends "base.html" %}

{% block head_title %}
    Create new post | {{ block.super }}
{% endblock %}

{% block content %}
    <div class="col-sm-8 col-sm-offset-2">
        <h1>Form</h1>
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-default" value="Create post">
        </form>
    </div>
{% endblock %}

templates/post_list.html
{% extends "base.html" %}

{% block content %}

    <div class="col-sm-8 col-sm-offset-2">
        <div class="page-header col-sm-12"><h1>{{ title }}</h1></div>
        {% if request.user.is_authenticated %}
        <a href="{% url 'posts:create' %}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-plus"></span> add new post</a>
        {% endif %}
        <h1></h1>
        {% for post in post_list %}
            <div class="row">
                <div class="col-sm-12">
                    <div class="thumbnail">
                        {% if post.image %}
                        <img src="{{ post.image.url }}" alt="" class="img-responsive">
                        {% endif %}
                        <div class="caption">
                            <h3><a href="{{ post.get_absolute_path }}">{{ post.title }}</a>
                                <small>{{ post.timestamp|timesince }} ago</small>
                            </h3>
                            <p>{{ post.get_short_content|linebreaks|truncatechars:120 }}</p>
                            {% if post.user.get_full_name %}
                            <p>Author: {{ post.user.get_full_name }}</p>
                            {% endif %}
                            <p><a href="{{ post.get_absolute_path }}" class="btn btn-primary" role="button">View</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
        {% endfor %}
        <div class="pagination">
    <span class="step-links">
        {% if post_list.has_previous %}
            <a href="?{{ page_request_var }}={{ post_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ post_list.number }} of {{ post_list.paginator.num_pages }}.
        </span>

        {% if post_list.has_next %}
            <a href="?{{ page_request_var }}={{ post_list.next_page_number }}"><span class="btn btn-primary">next</span></a>
        {% endif %}
    </span>
        </div>
    </div>
{% endblock %}